import LegalShell from "@/components/LegalShell";

export const metadata = { title: "Privacy Policy — AIPLB" };

export default function PrivacyPage() {
  return (
    <LegalShell title="Privacy & Cookies Policy" updated="2026-04-25">
      <h2>1. Data controller</h2>
      <p>
        Sakal Org SAS, operating AIPLB, is the data controller for personal
        data processed via the service. DPO contact:
        <a href="mailto:mehdi.sakalypr@gmail.com"> mehdi.sakalypr@gmail.com</a>.
      </p>

      <h2>2. Data we collect</h2>
      <ul>
        <li><strong>Account data:</strong> email address, hashed authentication tokens, plan and subscription state.</li>
        <li><strong>Company data:</strong> the URLs and competitor names you enter to be tracked.</li>
        <li><strong>Snapshots:</strong> processed extracts of public competitor pages, generated by AIPLB.</li>
        <li><strong>Operational data:</strong> request logs, error traces, IP address (hashed for spam prevention on the contact form).</li>
        <li><strong>Billing data:</strong> handled directly by Stripe; we store only the Stripe customer / subscription ID.</li>
        <li><strong>Chatbot data:</strong> messages exchanged with the website assistant, linked to a session ID (not your account by default).</li>
      </ul>

      <h2>3. Purposes & legal basis</h2>
      <ul>
        <li>Delivering the subscribed service — performance of contract (Art. 6.1.b GDPR).</li>
        <li>Billing, accounting, fraud prevention — legal obligation and legitimate interest (Art. 6.1.c & 6.1.f).</li>
        <li>Product analytics (aggregate, no individual profiling) — legitimate interest (Art. 6.1.f).</li>
        <li>Transactional email (magic link, digest, billing receipt) — performance of contract.</li>
        <li>Marketing email (rare, opt-out in every email) — legitimate interest of the controller.</li>
      </ul>

      <h2>4. Recipients</h2>
      <ul>
        <li>Vercel — application hosting (EU edge).</li>
        <li>Supabase — database hosting (EU, Frankfurt).</li>
        <li>Anthropic — LLM processing of public competitor content (USA, EU SCCs in place).</li>
        <li>Stripe — payment processing (Ireland & USA, EU SCCs).</li>
        <li>Resend — transactional email delivery (USA, EU SCCs).</li>
      </ul>
      <p>
        We do not sell or rent personal data to third parties. We do not use
        personal data to train any AI model. Anthropic's Enterprise terms
        explicitly forbid training on customer data.
      </p>

      <h2>5. Retention</h2>
      <ul>
        <li>Active account: data retained for the duration of the subscription.</li>
        <li>Cancelled account: account + competitors + snapshots retained for 12 months for legal continuity, then anonymised or deleted.</li>
        <li>Inactive account (no login for 24 months): we contact you; if no response within 30 days, the account is deleted.</li>
        <li>Billing data: 10 years (French commercial law).</li>
        <li>Server logs: 1 year (incident response).</li>
        <li>Contact form messages: 24 months active + 12 months archive.</li>
        <li>Chatbot messages: 6 months for product improvement, then deleted.</li>
      </ul>

      <h2>6. International transfers</h2>
      <p>
        Some processors (Anthropic, Stripe, Resend) are based in the USA.
        Transfers are covered by the EU Standard Contractual Clauses (SCCs)
        and supplementary measures (encryption in transit and at rest).
      </p>

      <h2>7. Your rights</h2>
      <p>Under GDPR you have the right to:</p>
      <ul>
        <li>Access your personal data.</li>
        <li>Request rectification of inaccurate data.</li>
        <li>Request erasure ("right to be forgotten").</li>
        <li>Restrict or object to processing.</li>
        <li>Data portability — export your account, competitors, snapshots and digests in a machine-readable format.</li>
        <li>Lodge a complaint with the CNIL (<a href="https://cnil.fr">cnil.fr</a>) or your national data protection authority.</li>
      </ul>
      <p>
        Exercise any right by emailing <a href="mailto:mehdi.sakalypr@gmail.com">mehdi.sakalypr@gmail.com</a>.
        We respond within 30 days.
      </p>

      <h2>8. Cookies</h2>
      <p>
        AIPLB only uses <strong>essential cookies</strong>:
      </p>
      <ul>
        <li><code>aici_session</code> — authentication session, HttpOnly, Secure, SameSite=Lax. Lifetime 30 days.</li>
        <li><code>aici_chat_session</code> (localStorage) — anonymous session ID for the chatbot, lifetime until cleared.</li>
      </ul>
      <p>
        We do not use marketing or advertising cookies. Vercel Analytics
        runs in privacy-friendly mode (no IP storage, no cross-site
        fingerprint), so no consent banner is required.
      </p>

      <h2>9. Security</h2>
      <p>
        TLS 1.3 in transit, AES-256 at rest (Supabase managed). Magic-link
        authentication, per-cookie HMAC signing, service-role keys held only
        server-side. Yearly access review.
      </p>

      <h2>10. Updates</h2>
      <p>
        Material changes to this policy will be notified by email at least
        30 days in advance.
      </p>
    </LegalShell>
  );
}
